#!/bin/bash

PARENT_NAMESPACE=/aporeto/se/demo/v1

function main() {
  local directory=$1
  [[ $directory ]] || { err "Usage:$0 directory"; return 2; }
  [ -d $directory ] && { err "Directory $directory exist. Remove directory or use a different name"; return 2; }
  [ -f $directory ] && { err "File $directory exist. Remove file or use a different name"; return 2; }

  parentdir=$(dirname $directory)
  [ -f $parentdir ] && { err "parent must be a directory not a file"; return 2; }
  [ -d $parentdir ] || { mkdir -p $parentdir; }
  cp -r lib $directory
  cd $directory
  mv settings _settings
  echo "export CLUSTER_NAME=$(basename $directory)" > settings
  echo "export PARENT_NAMESPACE=$PARENT_NAMESPACE" >> settings
  cat _settings >> settings
  rm _settings
  err "done"
}

err() { echo "$@" 1>&2; }

main $@
