#!/bin/bash -e

function main() {
  cd $(dirname $0)
  [ -f settings ] && . settings || { err "file settings not found"; return 2; }
  local fatal=0
  ./check-system || { fatal=1; }
  ./check-config || { fatal=1; }
  [ $fatal -eq 1 ] && { err "Unable to continue. See above."; return 2; }

  FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}

  local bucket="s3://k8s.${FQDN}"
  export KUBECONFIG=${PWD}/kube.config
  [ -f kube.config ] || { kops export kubecfg $FQDN --state=${bucket}/state; }
  kubectl get nodes --show-labels
}

err() { echo "$@" 1>&2; }

main $@
