#!/bin/bash

function main() {
  cd $(dirname $0)
  [ -f settings ] && . settings || { err "file settings not found"; return 2; }

  local fatal=0
  ./check-system || { fatal=1; }
  ./check-config || { fatal=1; }
  [ $fatal -eq 1 ] && { err "Unable to continue. See above."; return 2; }

  [[ "$CLOUD_PROVIDER" == "AWS" ]] || { err "Cloud provider must be AWS"; return 2; }

  FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
  aws ec2 --region $AWS_KUBE_REGION describe-instances --filters --filters "Name=iam-instance-profile.arn,Values=*$FQDN" --query "Reservations[*].Instances[*].PublicDnsName" --output text
}

err() { echo "$@" 1>&2; }

main $@
