#!/bin/bash -e

function main() {
  cd $(dirname $0)
  [ -f settings ] && . settings || { err "file settings not found"; return 2; }
  local fatal=0
  [[ $CLOUD_PROVIDER ]] || { err "Missing setting CLOUD_PROVIDER"; fatal=1; }
  [[ $CLUSTER_NAME ]] || { err "Missing setting CLUSTER_NAME"; fatal=1; }
  [[ $DNS_DOMAIN ]] || { err "Missing setting DNS_DOMAIN"; fatal=1; }
  [ $fatal -eq 1 ] && return 2
  FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
  [ -f kube.config ] && { err "kube.config exist"; return 0; }
  [[ "$CLOUD_PROVIDER" == "AWS" ]] && { _aws; return $?; }
}

_aws() {
  local fatal=0
  local bucket="s3://k8s.${FQDN}"
  export KUBECONFIG=${PWD}/kube.config
  set -x
  kops export kubecfg $FQDN --state=${bucket}/state
}

err() { echo "$@" 1>&2; }

main $@
