#!/bin/bash -e

function main() {
  cd $(dirname $0)
  [ -f settings ] && . settings || { err "file settings not found"; return 2; }
  local fatal=0
  [[ $CLOUD_PROVIDER ]] || { err "Missing setting CLOUD_PROVIDER"; fatal=1; }
  [[ $CLUSTER_NAME ]] || { err "Missing setting CLUSTER_NAME"; fatal=1; }
  [[ $DNS_DOMAIN ]] || { err "Missing setting DNS_DOMAIN"; fatal=1; }
  [[ $AWS_KUBE_CNI ]] || { err "Missing setting AWS_KUBE_CNI"; fatal=1; }
  [ $fatal -eq 1 ] && return 2

  [[ "$CLOUD_PROVIDER" == "AWS" ]] || { err "Cloud provider must be AWS"; return 2; }
  [[ "$AWS_KUBE_CNI" == "amazon-vpc-routed-eni" ]] || { err "CNI must be amazon-vpc-routed-eni"; return 2;  }

  FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
  local bucket="s3://k8s.${FQDN}"
  [ -f kube.config ] || {
    export KUBECONFIG=${PWD}/kube.config
    kops export kubecfg $FQDN --state=${bucket}/state
  }
  kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml
}

err() { echo "$@" 1>&2; }

main $@
